<?php
/**
 * Locale data for 'dua_CM'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 *  © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '5798',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0 %',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'dimɔ�?di',
      2 => 'ŋgɔndɛ',
      3 => 'sɔŋɛ',
      4 => 'diɓáɓá',
      5 => 'emiasele',
      6 => 'esɔpɛsɔpɛ',
      7 => 'madiɓɛ�?díɓɛ�?',
      8 => 'diŋgindi',
      9 => 'nyɛtɛki',
      10 => 'mayésɛ�?',
      11 => 'tiníní',
      12 => 'eláŋgɛ�?',
    ),
    'abbreviated' => 
    array (
      1 => 'di',
      2 => 'ŋgɔn',
      3 => 'sɔŋ',
      4 => 'diɓ',
      5 => 'emi',
      6 => 'esɔ',
      7 => 'mad',
      8 => 'diŋ',
      9 => 'nyɛt',
      10 => 'may',
      11 => 'tin',
      12 => 'elá',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'd',
      2 => 'ŋ',
      3 => 's',
      4 => 'd',
      5 => 'e',
      6 => 'e',
      7 => 'm',
      8 => 'd',
      9 => 'n',
      10 => 'm',
      11 => 't',
      12 => 'e',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'éti',
      1 => 'mɔ�?sú',
      2 => 'kwasú',
      3 => 'mukɔ�?sú',
      4 => 'ŋgisú',
      5 => 'ɗónɛsú',
      6 => 'esaɓasú',
    ),
    'abbreviated' => 
    array (
      0 => 'ét',
      1 => 'mɔ�?s',
      2 => 'kwa',
      3 => 'muk',
      4 => 'ŋgi',
      5 => 'ɗón',
      6 => 'esa',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'e',
      1 => 'm',
      2 => 'k',
      3 => 'm',
      4 => 'ŋ',
      5 => 'ɗ',
      6 => 'e',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ɓ.Ys',
      1 => 'mb.Ys',
    ),
    'wide' => 
    array (
      0 => 'ɓoso ɓwá yáɓe lá',
      1 => 'mbúsa kwédi a Yés',
    ),
    'narrow' => 
    array (
      0 => 'ɓ.Ys',
      1 => 'mb.Ys',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'idiɓa',
  'pmName' => 'ebyámu',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'dua' => 'duálá',
  ),
  'territories' => 
  array (
    'cm' => 'Cameroun',
  ),
);
