<?php
/**
 * Locale data for 'ig'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 *  © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '6546',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'NGN' => '₦',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Jenụwarị',
      2 => 'Febrụwarị',
      3 => 'Maachị',
      4 => 'Eprel',
      5 => 'Mee',
      6 => 'Juun',
      7 => 'Julaị',
      8 => 'Ọg�?�?st',
      9 => 'Septemba',
      10 => 'Ọktoba',
      11 => 'Novemba',
      12 => 'Disemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jen',
      2 => 'Feb',
      3 => 'Maa',
      4 => 'Epr',
      5 => 'Mee',
      6 => 'Juu',
      7 => 'Jul',
      8 => 'Ọg�?',
      9 => 'Sep',
      10 => 'Ọkt',
      11 => 'Nov',
      12 => 'Dis',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Mb�?sị Ụka',
      1 => 'M�?nde',
      2 => 'Tiuzdee',
      3 => 'Wenezdee',
      4 => 'T�?�?zdee',
      5 => 'Fraịdee',
      6 => 'Sat�?dee',
    ),
    'abbreviated' => 
    array (
      0 => 'Ụka',
      1 => 'M�?n',
      2 => 'Tiu',
      3 => 'Wen',
      4 => 'T�?�?',
      5 => 'Fraị',
      6 => 'Sat',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'T.K.',
      1 => 'A.K.',
    ),
    'wide' => 
    array (
      0 => 'Tupu Kristi',
      1 => 'Af�? Kristi',
    ),
    'narrow' => 
    array (
      0 => 'T.K.',
      1 => 'A.K.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'A.M.',
  'pmName' => 'P.M.',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'ak' => 'Akan',
    'am' => 'Amariikị',
    'ar' => 'Arabiikị',
    'be' => 'Belaruusu',
    'bg' => 'B�?lụgarịa',
    'bn' => 'Bengali',
    'cs' => 'Cheekị',
    'de' => 'Jamaan',
    'el' => 'Giriikị',
    'en' => 'Oyibo',
    'es' => 'Panya',
    'fa' => 'Peshan',
    'fr' => 'Fụrench',
    'ha' => 'Awụsa',
    'hi' => 'Hindi',
    'hu' => 'Magịya',
    'id' => 'Indonisia',
    'ig' => 'Igbo',
    'it' => 'Italo',
    'ja' => 'Japanese',
    'jv' => 'Java',
    'km' => 'Keme, Etiti',
    'ko' => 'Koria',
    'ms' => 'Maleyi',
    'my' => 'Mịanma',
    'ne' => 'Nepali',
    'nl' => 'D�?�?ch',
    'pa' => 'Punjabi',
    'pl' => 'Poliishi',
    'pt' => 'Potoki',
    'ro' => 'Rumenia',
    'ru' => 'R�?shan',
    'rw' => 'Rụwanda',
    'so' => 'Somali',
    'sv' => 'Sụwidiishi',
    'ta' => 'Tamụlụ',
    'th' => 'Taị',
    'tr' => 'T�?kiishi',
    'uk' => 'Ukureenị',
    'ur' => 'Urudu',
    'vi' => 'Viyetịnaamụ',
    'yo' => 'Yoruba',
    'zh' => 'Mandarịịnị',
    'zu' => 'Zulu',
  ),
  'territories' => 
  array (
    'bj' => 'Binin',
    'bm' => 'Bemuda',
    'cn' => 'Chaina',
    'ht' => 'Hati',
    'km' => 'Comorosu',
    'ly' => 'Libyia',
    'mv' => 'Maldivesa',
    'ng' => 'Nigeria',
  ),
);
