<?php
/**
 * Locale data for 'ii'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 *  © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '6443',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => '�?ꆪ',
      2 => '�?ꆪ',
      3 => 'ꌕꆪ',
      4 => 'ꇖꆪ',
      5 => 'ꉬꆪ',
      6 => 'ꃘꆪ',
      7 => '�?�ꆪ',
      8 => 'ꉆꆪ',
      9 => 'ꈬꆪ',
      10 => 'ꊰꆪ',
      11 => 'ꊰꊪꆪ',
      12 => 'ꊰꑋꆪ',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ꑭ�?�?',
      1 => '�?ꊂ�?',
      2 => '�?ꊂ�?',
      3 => '�?ꊂꌕ',
      4 => '�?ꊂꇖ',
      5 => '�?ꊂꉬ',
      6 => '�?ꊂꃘ',
    ),
    'abbreviated' => 
    array (
      0 => 'ꑭ�?',
      1 => '�?�?',
      2 => '�?�?',
      3 => '�?ꌕ',
      4 => '�?ꇖ',
      5 => '�?ꉬ',
      6 => '�?ꃘ',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '�?',
      1 => '�?',
      2 => '�?',
      3 => 'ꌕ',
      4 => 'ꇖ',
      5 => 'ꉬ',
      6 => 'ꃘ',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
    'wide' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
    'narrow' => 
    array (
      0 => 'ꃅꋊꂿ',
      1 => 'ꃅꋊꊂ',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ꎸꄑ',
  'pmName' => '�?�ꋒ',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'de' => 'ꄓꇩꉙ',
    'en' => 'ꑱꇩꉙ',
    'es' => 'ꑭꀠꑸꉙ',
    'fr' => 'ꃔꇩꉙ',
    'ii' => 'ꆈꌠꉙ',
    'it' => 'ꑴꄊꆺꉙ',
    'ja' => '�??ꀪꉙ',
    'pt' => '�??ꄨꑸꉙ',
    'pt_br' => 'ꀠꑟ�??ꄨꑸꉙ',
    'ru' => 'ꊉꇩꉙ',
    'und' => 'ꅉꀋꌠꅇꂷ',
    'zh' => '�??ꇩꉙ',
    'zh_hans' => '�?�?��??ꇩꉙ',
    'zh_hant' => 'ꀎ�?�??ꇩꉙ',
  ),
  'scripts' => 
  array (
    'arab' => 'ꀊ�?ꀨ�?�ꂷ',
    'cyrl' => 'ꀊꆨꌦ�?ꃚ�?�ꂷ',
    'hans' => '�?�?�ꉌꈲ�?�ꂷ',
    'hant' => 'ꀎ�?ꉌꈲ�?�ꂷ',
    'latn' => '�?ꄀ�?�ꂷ',
    'yiii' => 'ꆈꌠ�?�ꂷ',
    'zxxx' => '�?�ꀋꉆꌠ',
    'zzzz' => 'ꅉꀋ�?�ꌠ�?�ꂷ',
  ),
  'territories' => 
  array (
    'br' => 'ꀠꑭ',
    'cn' => '�??ꇩ',
    'de' => 'ꄓꇩ',
    'fr' => 'ꃔꇩ',
    'gb' => 'ꑱꇩ',
    'in' => 'ꑴꄗ',
    'it' => 'ꑴꄊꆺ',
    'jp' => '�??ꀪ',
    'ru' => 'ꊉꇆꌦ',
    'us' => 'ꂰꇩ',
    'zz' => 'ꃅꄷꅉꀋ�?�ꌠ',
  ),
);
