<?php
/**
 * Locale data for 'uz'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 *  © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '5912',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'UZS' => '�?ўм',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Январ',
      2 => 'Феврал',
      3 => 'Март',
      4 => '�?прел',
      5 => 'Май',
      6 => 'Июн',
      7 => 'Июл',
      8 => '�?вгу�?т',
      9 => 'Сент�?бр',
      10 => 'Окт�?бр',
      11 => '�?о�?бр',
      12 => 'Декабр',
    ),
    'abbreviated' => 
    array (
      1 => 'Янв',
      2 => 'Фев',
      3 => 'Мар',
      4 => '�?пр',
      5 => 'Май',
      6 => 'Июн',
      7 => 'Июл',
      8 => '�?вг',
      9 => 'Сен',
      10 => 'Окт',
      11 => '�?о�?',
      12 => 'Дек',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Я',
      2 => 'Ф',
      3 => 'М',
      4 => '�?',
      5 => 'М',
      6 => 'И',
      7 => 'И',
      8 => '�?',
      9 => 'С',
      10 => 'О',
      11 => '�?',
      12 => 'Д',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => '�?кшанба',
      1 => 'душанба',
      2 => '�?ешанба',
      3 => 'чоршанба',
      4 => 'пайшанба',
      5 => 'жума',
      6 => 'шанба',
    ),
    'abbreviated' => 
    array (
      0 => 'Якш',
      1 => 'Душ',
      2 => 'Сеш',
      3 => 'Чор',
      4 => 'Пай',
      5 => 'Жум',
      6 => 'Шан',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Я',
      1 => 'Д',
      2 => 'С',
      3 => 'Ч',
      4 => 'П',
      5 => 'Ж',
      6 => 'Ш',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'ar' => '�?рабча',
    'de' => 'Олмонча',
    'en' => 'Инглизча',
    'es' => 'И�?панча',
    'fr' => 'Французча',
    'hi' => 'Ҳиндча',
    'it' => 'Итал�?нча',
    'ja' => 'Японча',
    'pt' => 'Португалча',
    'ru' => 'Ру�?ча',
    'uz' => 'Ўзбек',
    'zh' => 'Хитойча',
  ),
  'scripts' => 
  array (
    'arab' => '�?раб',
    'cyrl' => 'Кирил',
    'latn' => 'Лотин',
  ),
  'territories' => 
  array (
    'af' => '�?фғони�?тон',
    'br' => 'Бразили�?',
    'cn' => 'Хитой',
    'de' => 'Олмони�?',
    'fr' => 'Франци�?',
    'gb' => 'Бирлашган Қироллик',
    'in' => 'Ҳинди�?тон',
    'it' => 'Итали�?',
    'jp' => 'Япони�?',
    'ru' => 'Ро�?�?и�?',
    'us' => 'Қўшма Штатлар',
    'uz' => 'Ўзбеки�?тон',
  ),
);
