<?php
/**
 * Locale data for 'uz_Arab_AF'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 *  © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '4123',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '٪',
    'plusSign' => '+',
    'minusSign' => '−',
    'exponential' => '×۱۰^',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'UZS' => '�?ўм',
    'AFN' => '؋',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'جنوری',
      2 => '�?بروری',
      3 => 'مارچ',
      4 => 'اپریل',
      5 => 'می',
      6 => 'جون',
      7 => 'جولای',
      8 => 'اگست',
      9 => 'سپتمبر',
      10 => 'اکتوبر',
      11 => 'نومبر',
      12 => 'دسمبر',
    ),
    'abbreviated' => 
    array (
      1 => 'جنو',
      2 => '�?بر',
      3 => 'مار',
      4 => 'اپر',
      5 => 'مـی',
      6 => 'جون',
      7 => 'جول',
      8 => 'اگس',
      9 => 'سپت',
      10 => 'اکت',
      11 => 'نوم',
      12 => 'دسم',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Я',
      2 => 'Ф',
      3 => 'М',
      4 => '�?',
      5 => 'М',
      6 => 'И',
      7 => 'И',
      8 => '�?',
      9 => 'С',
      10 => 'О',
      11 => '�?',
      12 => 'Д',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'یکشنبه',
      1 => 'دوشنبه',
      2 => 'سه‌شنبه',
      3 => 'چهارشنبه',
      4 => 'پنجشنبه',
      5 => 'جمعه',
      6 => 'شنبه',
    ),
    'abbreviated' => 
    array (
      0 => 'ی.',
      1 => 'د.',
      2 => 'س.',
      3 => 'چ.',
      4 => 'پ.',
      5 => 'ج.',
      6 => 'ش.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Я',
      1 => 'Д',
      2 => 'С',
      3 => 'Ч',
      4 => 'П',
      5 => 'Ж',
      6 => 'Ш',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'ق.م.',
      1 => 'م.',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y نچی ییل d نچی MMMM EEEE کونی',
    'long' => 'd نچی MMMM y',
    'medium' => 'd MMM y',
    'short' => 'yyyy/M/d',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss (zzzz)',
    'long' => 'H:mm:ss (z)',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'rtl',
  'languages' => 
  array (
    'ar' => '�?рабча',
    'de' => 'Олмонча',
    'en' => 'Инглизча',
    'es' => 'И�?панча',
    'fr' => 'Французча',
    'hi' => 'Ҳиндча',
    'it' => 'Итал�?нча',
    'ja' => 'Японча',
    'pt' => 'Португалча',
    'ru' => 'Ру�?ча',
    'uz' => 'اۉزب�?ک',
    'zh' => 'Хитойча',
    'fa' => 'دری',
    'ps' => 'پشتو',
  ),
  'scripts' => 
  array (
    'arab' => '�?раб',
    'cyrl' => 'Кирил',
    'latn' => 'Лотин',
  ),
  'territories' => 
  array (
    'af' => 'ا�?غانستان',
    'br' => 'Бразили�?',
    'cn' => 'Хитой',
    'de' => 'Олмони�?',
    'fr' => 'Франци�?',
    'gb' => 'Бирлашган Қироллик',
    'in' => 'Ҳинди�?тон',
    'it' => 'Итали�?',
    'jp' => 'Япони�?',
    'ru' => 'Ро�?�?и�?',
    'us' => 'Қўшма Штатлар',
    'uz' => 'Ўзбеки�?тон',
  ),
);
