<?php
/**
 * Locale data for 'uz_Latn'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 *  © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '5882',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'UZS' => 'soʼm',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Yanvar',
      2 => 'Fevral',
      3 => 'Mart',
      4 => 'Aprel',
      5 => 'May',
      6 => 'Iyun',
      7 => 'Iyul',
      8 => 'Avgust',
      9 => 'Sentyabr',
      10 => 'Oktyabr',
      11 => 'Noyabr',
      12 => 'Dekabr',
    ),
    'abbreviated' => 
    array (
      1 => 'Yanv',
      2 => 'Fev',
      3 => 'Mar',
      4 => 'Apr',
      5 => 'May',
      6 => 'Iyun',
      7 => 'Iyul',
      8 => 'Avg',
      9 => 'Sen',
      10 => 'Okt',
      11 => 'Noya',
      12 => 'Dek',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Y',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'I',
      7 => 'I',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'yakshanba',
      1 => 'dushanba',
      2 => 'seshanba',
      3 => 'chorshanba',
      4 => 'payshanba',
      5 => 'cuma',
      6 => 'shanba',
    ),
    'abbreviated' => 
    array (
      0 => 'Yaksh',
      1 => 'Dush',
      2 => 'Sesh',
      3 => 'Chor',
      4 => 'Pay',
      5 => 'Cum',
      6 => 'Shan',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Y',
      1 => 'D',
      2 => 'S',
      3 => 'C',
      4 => 'P',
      5 => 'C',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'ar' => 'arabcha',
    'de' => 'olmoncha',
    'en' => 'inglizcha',
    'es' => 'ispancha',
    'fr' => 'fransuzcha',
    'hi' => 'hindcha',
    'it' => 'italyancha',
    'ja' => 'yaponcha',
    'pt' => 'portugalcha',
    'ru' => 'ruscha',
    'uz' => 'oʼzbekcha',
    'zh' => 'xitoycha',
  ),
  'scripts' => 
  array (
    'arab' => '�?раб',
    'cyrl' => 'Kiril',
    'latn' => 'Lotin',
  ),
  'territories' => 
  array (
    'af' => 'Afgʼoniston',
    'br' => 'Braziliya',
    'cn' => 'Xitoy',
    'de' => 'Olmoniya',
    'fr' => 'Fransiya',
    'gb' => 'Birlashgan Qirollik',
    'in' => 'Hindiston',
    'it' => 'Italiya',
    'jp' => 'Yaponiya',
    'ru' => 'Rossiya',
    'us' => 'Qoʼshma Shtatlar',
    'uz' => 'Oʼzbekiston',
  ),
);
