<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administrace</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurá!</strong> To je pro tuto chvíli vše.',
  '<strong>Modules</strong>' => '<strong>Moduly</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Odtud můžete jako správce systému řídit celou síť.<br><br>Nyní zmíníme jen sekci Moduly, jinak v každé sekci najdete krátký popis toho, co se v ní dá nastavovat.',
  'You are currently in the tools menu. From here you can access the Profiler online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Toto je menu administace. Můžete tudy vstoupit např. k online obchodu Profileru, ze kterého můžete instalovat nové moduly.<br><br>Jak jsme již zmínili, moduly rozšiřují možnou funkcionalitu v prostorech.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.Profiler.org.<br><br>Stay tuned. :-)' => 'Nyní jste se nau�?il(a) vše o nejdůležitějších vlastnostech a nastaveních. Výchozí nastavení umožňuje Profiler za�?ít používat okamžitě, směle tedy do toho.<br><br>Doufáme, že se vám i dalším uživatelům bude Profiler líbit a rádi uvítáme podněty všeho druhu – ty nám pomohou Profiler vylepšit. Rádi budeme i za vaši podporu. Nebojte se nás proto kontaktovat prostřednictvím našich stránek www.Profiler.org.<br><br>Děkujeme za vaše rozhodnutí pro Profiler!',
);
