<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' Remove panel' => '',
  '<strong>Tutorial</strong> Guides' => '<strong>Hvordan man bruger Profiler</strong>',
  '<strong>Guide:</strong> Administration (Modules)' => '<strong>Guide: </strong> Administration (Moduler)',
  '<strong>Guide:</strong> Overview' => '<strong>Guide: </strong> Oversigt',
  '<strong>Guide:</strong> Groups' => '<strong>Guide: </strong> Grupper',
  '<strong>Guide:</strong> User profile' => '<strong>Guide: </strong> Bruger profil',
  'Get to know your way around Profiler\'s most important features with the following guides:' => '<strong>Lær Profiler\'s vigtigste funktioner at kende</strong>',
);
