<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Account</strong> Menu' => '<strong>Bruger</strong> Menu',
  '<strong>Notifications</strong>' => '<strong>Notifikationer</strong>',
  '<strong>Space</strong> Menu' => '<strong>Bruger</strong> Menu',
  '<strong>Start</strong> space guide' => '<strong>Gruppe</strong> Menu',
  'Don\'t lose track of things!<br /><br />This icon will keep you informed of activities and posts that concern you directly.' => 'Midst ikke overblikket! Dette ikon vil holde dig informeret om aktiviteter og posts der vedrøre dig direkte.',
  'The account menu gives you access to your private settings and allows you to manage your public profile.' => 'Denne bruger menu giver dig adgang til dine private indstillinger og gøre dig i stand til at administrer din offentlige profil.',
  'This is the most important menu and will probably be the one you use most often!<br><br>Access all the spaces you have joined and create new spaces here.<br><br>The next guide will show you how:' => 'Dette er den mest vigtigeste menu og vil højst sandsyneligt være den du bruger mest. <br> <br>Få adgang til alle dine grupper hér. <br> <br>Den næste guide vil vise dig:',
);
