<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<b>Nobody wrote something yet.</b><br>Make the beginning and post something...' => '<b>Ingen har skrevet noget endu.</b><br>Lav begyndelsen, og lav et indlæg...',
  '<b>This profile stream is still empty</b>' => '<b>Denne profils tidslinje er stadig tom</b>',
  '<b>This space is still empty!</b><br>Start by posting something here...' => '<b>Denne gruppe er stadig tom!</b><br>Start med at lave et indlæg...',
  '<b>Your dashboard is empty!</b><br>Post something on your profile or join some spaces!' => '<b>Din forside er tom!</b><br>Lav et indlæg på din profil, eller tildmæld dig til nogle grupper!',
  '<b>Your profile stream is still empty</b><br>Get started and post something...' => '<b>Din profils tidslinje er stadig tom</b><br>Start ud med at lave et indlæg...',
  'Back to stream' => 'Tilbage til forside',
  'Content with attached files' => 'Indhold med vedhæftet filer',
  'Created by me' => 'Lavet af mig',
  'Creation time' => 'Tid at indlæget blev lavet',
  'Filter' => 'Filtré',
  'Include archived posts' => 'Inkludér arkiveret indlæg',
  'Last update' => 'Sidste opdatering',
  'Nothing found which matches your current filter(s)!' => 'Intet var fundet, der matchede dine filter/filtre',
  'Only private posts' => 'Kun private indlæg',
  'Only public posts' => 'Kun offentlige indlæg',
  'Posts only' => 'Kun indlæg',
  'Posts with links' => 'Indlæg med links',
  'Show all' => 'Vis alle',
  'Sorting' => 'Sortering',
  'Where I´m involved' => 'Hvor jeg er involveret',
);
