<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Invalid link! Please make sure that you entered the entire url.' => 'Link er invalid! er du sikker på at du har skrevet linket rigtigt?',
  'Save profile' => 'Gem Profil',
  'Saved' => 'Gemt',
  'The entered e-mail address is already in use by another user.' => 'Email addressen du skrev, er allerede i brug af en anden bruger.',
  'You cannot change your e-mail address here.' => 'Du kan ikke ændre din email addresse her.',
  'You cannot change your password here.' => 'Du kan ikke ændre dit kodeord her.',
);
