<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => 'Om',
  'Birthday' => 'Fødselsdag',
  'City' => 'By',
  'Contains Mature Content' => 'Indeholder modent indhold',
  'Country' => 'Land',
  'Custom' => '',
  'Facebook URL' => 'Facebook Link',
  'Fax' => 'Fax',
  'Female' => 'Kvinde',
  'Firstname' => 'Fornavn',
  'Flickr URL' => 'Flicker Link',
  'Gender' => 'Køn',
  'Google+ URL' => 'Google+ link',
  'Hide year in profile' => 'Skjul din profil',
  'Lastname' => 'Efternavn',
  'LinkedIn URL' => 'LinkedIn Link',
  'MSN' => 'MSN',
  'Male' => 'Mand',
  'Mobile' => 'Mobil',
  'MySpace URL' => 'MySpace Link',
  'Phone Private' => 'Telefon (Privat)',
  'Phone Work' => 'Telefon (Arbejde)',
  'Skype Nickname' => 'Skype Brugernavn',
  'State' => 'Stat',
  'Street' => 'Gade',
  'Title' => 'Titel',
  'Twitter URL' => 'Twitter Link',
  'Url' => 'Link',
  'User' => 'Bruger',
  'Vimeo URL' => 'Vimeo Link',
  'XMPP Jabber Address' => 'XMPP Jabber Addresse',
  'Xing URL' => 'Xing Link',
  'Youtube URL' => 'Youtube Link',
  'Zip' => 'Postkode',
);
