<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Created at' => 'Lavet den',
  'Created by' => 'Lavet af',
  'Description' => 'Beskrivelse',
  'Editable' => 'Kan Redigeres',
  'Field Type could not be changed!' => 'Felttype kunne ikke blive skiftet!',
  'Fieldtype' => 'Felttype',
  'ID' => 'ID',
  'Internal Name' => 'Internt navn',
  'Internal name already in use!' => 'Internt navn er allerede i brug!',
  'Internal name could not be changed!' => 'Internt navn kunne ikke blive skiftet!',
  'Invalid field type!' => 'Invalid felttype',
  'LDAP Attribute' => 'LDAP Attribut',
  'Module' => 'Modul',
  'Only alphanumeric characters allowed!' => 'Kun alphanumeriske karaktere tilladt',
  'Profile Field Category' => 'Profil felt kategori',
  'Required' => 'Nødvendig',
  'Show at registration' => 'Vis ved registrering',
  'Sort order' => 'Sorterings rækkefølge',
  'Title' => 'Titel',
  'Translation Category ID' => 'Oversættelses Kategori ID',
  'Type Config' => 'Type Konfiguration',
  'Updated at' => 'Opdateret ved ',
  'Updated by' => 'Opdateret af',
  'Visible' => 'Synlig',
);
