<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Email</strong> Notifications' => '<strong>Email</strong> Notifkationer',
  'Activities' => 'Aktiviteter',
  'Always' => 'Altid',
  'Daily summary' => 'Daglig resumé',
  'Get an email, by every activity from other users you follow or work<br>together in workspaces.' => 'Send mig en mail, for vær aktivitet fra andre brugere du følger eller du er i arbejdsgrupper med',
  'Get an email, when other users comment or like your posts.' => 'Send mig en mail, når andre brugere kommentere eller kan lide dine indlæg.',
  'Never' => 'Aldrig',
  'Notifications' => 'Notifikationer',
  'Save' => 'Gem',
  'When I´m offline' => 'Når jeg er offline',
);
