<?php
return array (
  '<strong>Administration</strong>' => '<strong>�?дмини�?трирование</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Ура!</strong> Это в�?е на �?егодн�?.',
  '<strong>Modules</strong>' => '<strong>Модули</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'В роли админи�?тратора вы можете управл�?ть в�?ей платформой от�?юда.<br><br> Кроме модулей мы не будет подробно ни на чем о�?танавливать�?�?, так как у каждого �?лемента е�?ть �?вое короткое опи�?ание.',
  'You are currently in the tools menu. From here you can access the Profiler online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Сейча�? вы в меню ин�?трументов. От�?юда вы можете получить до�?туп к маркету Profiler, откуда можно у�?тановить дополнительные ин�?трументы налету. <br><br> Как уже упоминало�?ь, ин�?трументы увеличивают работо�?по�?боно�?ть ваших Про�?тран�?тв. ',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.Profiler.org.<br><br>Stay tuned. :-)' => 'Вы уже узнали почти о в�?ех о�?новных возможно�?т�?х и на�?тройках, и готовы к и�?пользованию платформы.<br><br>�?адеем�?�?, вы и в�?е будущие пользовател�? получат удоволь�?твие от и�?пользовани�? �?айта. Будем рады любым предложени�?м и замечани�?м, которые помогут улучшить проект. О�?тавайте�?ь на �?в�?зи и пишите нам в любое врем�?. :-)',
);
