<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Administration</strong>' => '<strong>管�?�</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>�?�喜你!</strong> 完�?了该�?�导.',
  '<strong>Modules</strong>' => '<strong>模�?�</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => '作为管�?�员，您�?�以从这里管�?�整个平�?�。<br> <br>除了模�?�，我们�?会在这里详细一点，�?个都有自己的简短�??述的地方',
  'You are currently in the tools menu. From here you can access the Profiler online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => '你目�?在“工具�?�?��?�。从这里你�?�以访问Profiler在线市场，在那里你�?�以安装�?断增加的工具。<br> <br>正如已�?�??到的，该工具�?�以增加您的空间特性。',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.Profiler.org.<br><br>Stay tuned. :-)' => '你现在已�?知�?�了所有最�?�?的功能和设置，�?�将开始使用平�?�。<br> <br>我们希望你和所有未�?�的用户将享�?�本网站。我们期待任何建议或支�?。通过www.Profiler感到自由与我们�?�系。org。<br> <br>：-）',
);
